name: CI-CD Demo

on:
  push:
    branches: [main]            # chạy khi push vào nhánh main
  pull_request:
    branches: [main]            # chạy khi tạo PR vào main

jobs:
  # ---------------- CI ----------------
  build:
    runs-on: windows-latest     # đổi ubuntu-latest nếu dự án Linux
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Compiling code..."
          echo "Build successful!"

      # nếu cần gói artefact build để deploy
      - name: Zip build
        run: Compress-Archive -Path . -Destination build.zip

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "Running tests..."
          echo "All tests passed!"

  # ---------------- CD ----------------
  deploy:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: write            # cho phép tạo Release
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build            # tải build.zip về

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          artifacts: build.zip
          generateReleaseNotes: true
