name: CI-CD Demo

on:
  push:
    branches: [main]            # chạy khi push vào nhánh main
  pull_request:
    branches: [main]

jobs:
  # ---------------- CI ----------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Compiling code..."
          echo "Build successful!"

      - name: Upload site files
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: .               # upload toàn bộ nội dung repo (gồm index.html)

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          echo "Running tests..."
          echo "All tests passed!"

  # ---------------- CD ----------------
  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .        # thư mục chứa index.html
